version: '3'

services:
  fr-db:
    container_name: fr-db
    build:
      context: database
      dockerfile: Dockerfile
    env_file: database/.env.local
    ports:
      - 5432:5432
    volumes:
      - ./database:/usr/src/database/
      - fr-db-data:/var/lib/postgresql/data

  fr-api:
    container_name: fr-api
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - APP_TARGET=local
      - NODE_ENV=development
    volumes:
      - ./api:/usr/src/app
      - fr-api-nodemodules:/usr/src/app/node_modules
    ports:
      - 8082:8082
    depends_on:
      - fr-db

  fr-frontend:
    container_name: fr-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - APP_TARGET=local
      - NODE_ENV=development
    ports:
      - 3002:3002
    volumes:
      - ./frontend:/usr/src/app
      - fr-frontend-nodemodules:/usr/src/app/node_modules
    depends_on:
      - fr-api

volumes:
  fr-db-data:
  fr-api-nodemodules:
  fr-frontend-nodemodules:
